/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package admin;

/**
 *
 * @author marcelosiedler
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuGerenciarPessoa = new javax.swing.JMenuItem();
        mnuListarPessoa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuGerenciarCidade = new javax.swing.JMenuItem();
        mnuListarCidade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Pessoa");

        mnuGerenciarPessoa.setText("Gerenciar");
        mnuGerenciarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGerenciarPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGerenciarPessoa);

        mnuListarPessoa.setText("Listar");
        mnuListarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuListarPessoa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cidade");

        mnuGerenciarCidade.setText("Gerenciar");
        mnuGerenciarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGerenciarCidadeActionPerformed(evt);
            }
        });
        jMenu2.add(mnuGerenciarCidade);

        mnuListarCidade.setText("Listar");
        mnuListarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarCidadeActionPerformed(evt);
            }
        });
        jMenu2.add(mnuListarCidade);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuGerenciarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGerenciarPessoaActionPerformed
        // TODO add your handling code here:
        pessoaManter tela = new pessoaManter();
        //fechar apenas a janela
        tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuGerenciarPessoaActionPerformed

    private void mnuListarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarCidadeActionPerformed
        // TODO add your handling code here:
        cidadeListar tela = new cidadeListar();
        //fechar apenas a janela
        tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuListarCidadeActionPerformed

    private void mnuGerenciarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGerenciarCidadeActionPerformed
        // TODO add your handling code here:
        cidadeManter tela = new cidadeManter();
        //fechar apenas a janela
        tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuGerenciarCidadeActionPerformed

    private void mnuListarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarPessoaActionPerformed
        // TODO add your handling code here:
        pessoaListar tela = new pessoaListar();
        //fechar apenas a janela
        tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuListarPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuGerenciarCidade;
    private javax.swing.JMenuItem mnuGerenciarPessoa;
    private javax.swing.JMenuItem mnuListarCidade;
    private javax.swing.JMenuItem mnuListarPessoa;
    // End of variables declaration//GEN-END:variables
}
